doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        url: '%env(CLUB_DB_TYPE)%://%env(resolve:CLUB_DB_USER)%:%env(resolve:CLUB_DB_PASSWORD)%@%env(CLUB_DB_HOST)%:%env(CLUB_DB_PORT)%/%env(CLUB_DB_NAME)%'
        server_version: '%env(CLUB_DB_VERSION)%'
        charset: '%env(CLUB_DB_CHARSET)%'    
#    dbal:
#        connections:
#            club:
#                url: '%env(CLUB_DB_TYPE)%://%env(resolve:CLUB_DB_USER)%:%env(resolve:CLUB_DB_PASSWORD)%@%env(CLUB_DB_HOST)%:%env(CLUB_DB_PORT)%/%env(CLUB_DB_NAME)%'
#                server_version: '%env(CLUB_DB_VERSION)%'
#                charset: '%env(CLUB_DB_CHARSET)%'
#            datawarehouse:
#                url: '%env(resolve:DW_DATABASE_URL)%'
#            traitement:
#                url: '%env(resolve:PROCESS_DATABASE_URL)%'
#        default_connection: club
    orm:
        default_entity_manager: club
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
#        entity_managers:
#            club:
#                connection: club
#                mappings:
#                    Main:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity/Main'
#                        prefix: 'App\Entity\Main'
#                        alias: Main
#            customer:
#                connection: customer
#                mappings:
#                    Customer:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity/Customer'
#                        prefix: 'App\Entity\Customer'
#                        alias: Customer

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
