controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
 
media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
