# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    sonata.media.provider.svg:
        class: App\Provider\Media\SVGProvider
        arguments:
            - sonata.media.provider.svg
            - '@sonata.media.filesystem.local'
            - '@sonata.media.cdn.server'
            - '@sonata.media.generator.default'
            - '@sonata.media.thumbnail.format'
            - allowed_extensions: ['svg']
            - allowed_mime_types: ['image/svg+xml']
        calls:
            -
                - setTemplates
                - - helper_thumbnail: 'media/svg/thumbnail.html.twig'
                    helper_view : 'media/svg/view.html.twig'
                    
#            -
#                - setTemplates
#                - - helper_thumbnail: '@@SonataMedia/Provider/thumbnail.html.twig'
#                    helper_view: '@@SonataMedia/Provider/view_vimeo.html.twig'
#            -
#                - setResizer
#                - ['@sonata.media.resizer.simple']
        tags:
            - { name: sonata.media.provider }
        public: true
